name: Python Test

on:
  push:
    branches:
      - main  # or your default branch
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change as necessary

      - name: Run script
        run: |
          DIFF=$(git show --name-only HEAD | grep '.csv' || true)
          echo $DIFF
          
          python -c "
          import subprocess
          import logging

          logging.basicConfig(level=logging.ERROR)
          logger = logging.getLogger()

          try:
              files = subprocess.check_output(
                  'git diff --name-only HEAD^ HEAD | grep \'.csv\' || true',
                  shell=True,
                  text=True
              ).strip().splitlines()

              print('Modified CSV files:', files)
          except subprocess.CalledProcessError as e:
              logger.error('Error fetching modified files', extra={'error': str(e)})
          "
