name: Check PR Files

on:
  push:
    branches:
      - main

jobs:
  check-pr-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Get changed files from PR
        id: get_changed_files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ${{github.event}}
          pwd
          echo $HOME
          ls -la
          # pr_number=${{ inputs.pr_number }}
          # files=$(gh pr view ${{ inputs.pr_number }} --json files --jq '.files[].path')
          # for file in $files; do
          #   echo "Processing file: $file"
          # done
