name: Check PR Files

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        default: '1'

jobs:
  check-pr-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files from PR
        id: get_changed_files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          changed_files=$(gh pr view $pr_number --json files --jq '.files[].path')
          echo "Changed files: $changed_files"
          echo "::set-output name=files::$changed_files"

      - name: Process changed files
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.get_changed_files.outputs.files }}"
          for file in "${files[@]}"; do
            echo "Processing file: $file"
            # Add your processing logic here
          done
