name: Check PR Files

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        default: '1'

jobs:
  check-pr-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files from PR
        id: get_changed_files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=${{ github.event.inputs.pr_number }}
          files=$(gh pr view 6 --json files --jq '.files[].path')
          for file in $files; do
            echo "Processing file: $file"
          done
