name: Apply Job

on:
  push:
    branches:
      - main
jobs:
  sending-post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sending POST request
        run: |
          files=git diff --name-only HEAD^ HEAD
          echo $files
