name: Python Test

on:
  push:
    branches:
      - main  # or your default branch
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Change as necessary

          echo "Pull Request Number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV

          FILES=$(curl -s "$BASE_URL/repos/$OWNER/$REPO/pulls/$PR_NUMBER/files" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json")
          echo "$RESPONSE"
        