name: Apply Job

on:
  push:
    branches:
      - main
jobs:
  sending-post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Sending POST request
        run: |
          files=$(gh pr view 6 --files)
          echo $files
