name: Apply Job

on:
  push:
    branches:
      - main
jobs:
  sending-post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$(gh pr view 6)
          echo $files
